name = "CutCell"
uuid = "be28856a-4c0c-4f32-807d-52adcc26ec06"
authors = ["Arjun Narayanan"]
version = "0.1.0"

[deps]
CartesianMesh = "c3f3b8a2-2e3b-4b62-84bb-76319e98af94"
ImplicitDomainQuadrature = "215a9a07-c97b-423e-a99e-05c6f7357eae"
LinearAlgebra = "37e2e46d-f89d-539d-b4ee-838fcccc9c8e"
PolynomialBasis = "776a168a-1973-4f1d-bada-3c06b642fffd"
SparseArrays = "2f01184e-e22b-5df5-ae63-d93ebab69eaf"

[compat]
julia = "1"

[extras]
SafeTestsets = "1bc83da4-3b8d-516f-aca4-4fe02f6d838f"
Test = "8dfed614-e22c-5e08-85e1-65c5234f0b40"

[targets]
test = ["Test", "SafeTestsets"]
